### ISSUE TITLE
Errors when selecting bosses

### ISSUE THREAD

**Issue by tehKD** [Road-block/MizusRaidTracker#1]
Im getting this error when i select a boss in the overview.
It also doesnt track all items... Im getting the popup and all but i cant see the item in the overview frame.

`25x ...aceMizusRaidTracker\MizusRaidTracker_GUI.lua:126: attempt to call method 'SetBackdrop' (a nil value)
[string "@MizusRaidTracker\MizusRaidTracker_GUI.lua"]:126: in function `fnDoCellUpdate'
[string "@MizusRaidTracker\libs\LibST\core.lua"]:793: in function `Refresh'
[string "@MizusRaidTracker\libs\LibST\core.lua"]:340: in function `SortData'
[string "@MizusRaidTracker\libs\LibST\core.lua"]:592: in function `SetData'
[string "@MizusRaidTracker\MizusRaidTracker_GUI.lua"]:1481: in function `MRT_GUI_BossLootTableUpdate'
[string "@MizusRaidTracker\MizusRaidTracker_GUI.lua"]:1383: in function `MRT_GUI_BossDetailsTableUpdate'
[string "@MizusRaidTracker\MizusRaidTracker_GUI.lua"]:1378: in function `MRT_GUI_RaidDetailsTableUpdate'
[string "@MizusRaidTracker\MizusRaidTracker_GUI.lua"]:344: in function `MRT_GUI_Toggle'
[string "@MizusRaidTracker\MizusRaidTracker-v0.85.6-bcc.lua"]:544: in function `OnClick'
[string "@Bazooka\Bazooka-v2.9.3.lua"]:1418: in function <Bazooka\Bazooka.lua:1415>

Locals:
rowFrame = ScrollTable4Row1 {
 0 = <userdata>
 highlight = <unnamed> {
 }
 cols = <table> {
 }
}
cellFrame = ScrollTable4Row1col7 {
 0 = <userdata>
 text = ScrollTable4Row1col7text {
 }
}
data = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
}
cols = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
}
row = 1
realrow = 1
column = 7
fShow = true
self = <table> {
 sorttable = <table> {
 }
 filtered = <table> {
 }
 SortData = <function> defined @MizusRaidTracker\libs\LibST\core.lua:310
 cols = <table> {
 }
 GetDefaultHighlightBlank = <function> defined @MizusRaidTracker\libs\LibST\core.lua:450
 EnableSelection = <function> defined @MizusRaidTracker\libs\LibST\core.lua:484
 scrollframe = ScrollTable4ScrollFrame {
 }
 Hide = <function> defined @MizusRaidTracker\libs\LibST\core.lua:300
 offset = 0
 GetRow = <function> defined @MizusRaidTracker\libs\LibST\core.lua:599
 showing = true
 Show = <function> defined @MizusRaidTracker\libs\LibST\core.lua:290
 DefaultEvents = <table> {
 }
 SetWidth = <function> defined @MizusRaidTracker\libs\LibST\core.lua:43
 Filter = <function> defined @MizusRaidTracker\libs\LibST\core.lua:424
 SetFilter = <function> defined @MizusRaidTracker\libs\LibST\core.lua:433
 SetData = <function> defined @MizusRaidTracker\libs\LibST\core.lua:589
 SetSelection = <function> defined @MizusRaidTracker\libs\LibST\core.lua:500
 DoFilter = <function> defined @MizusRaidTracker\libs\LibST\core.lua:438
 isMinimalDataformat = true
 ClearSelection = <function> defined @MizusRaidTracker\libs\LibST\core.lua:492
 data = <table> {
 }
 GetCell = <function> defined @MizusRaidTracker\libs\LibST\core.lua:607
 fSelect = true
 rows = <table> {
 }
 SetHeight = <function> defined @MizusRaidTracker\libs\LibST\core.lua:38
 SetDisplayRows = <function> defined @MizusRaidTracker\libs\LibST\core.lua:122
 FireUserEvent = <function> defined @MizusRaidTracker\libs\LibST\core.lua:65
 GetDefaultHighlight = <function> defined @MizusRaidTracker\libs\LibST\core.lua:465
 rowHeight = 30
 displayRows = 6
 defaulthighlightblank = <table> {
 }
 defaulthighlight = <table> {
 }
 RegisterEvents = <function> defined @MizusRaidTracker\libs\LibST\core.lua:78
 head = ScrollTable4Head {
 }
 SetDefaultHighlightBlank = <function> defined @MizusRaidTracker\libs\LibST\core.lua:454
 Refresh = <function> defined @MizusRaidTracker\libs\LibST\core.lua:764
 IsRowVisible = <function> defined @MizusRaidTracker\libs\LibST\core.lua:624
 SetDisplayCols = <function> defined @MizusRaidTracker\libs\LibST\core.lua:203
 RowIsVisible = <function> defined @MizusRaidTracker\libs\LibST\core.lua:624
 SetDefaultHighlight = <function> defined @MizusRaidTracker\libs\LibST\core.lua:469
 events = <table> {
 }
 DoCellUpdate = <function> defined @MizusRaidTracker\libs\LibST\core.lua:518
 GetSelection = <function> defined @MizusRaidTracker\libs\LibST\core.lua:509
 frame = ScrollTable4 {
 }
 SetHighLightColor = <function> defined @MizusRaidTracker\libs\LibST\core.lua:57
 CompareSort = <function> defined @MizusRaidTracker\libs\LibST\core.lua:356
}
lootNote = nil
(*temporary) = nil
(*temporary) = ScrollTable4Row1col7 {
 0 = <userdata>
 text = ScrollTable4Row1col7text {
 }
}
(*temporary) = nil
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
`

**Comment by Road-block** [comment]
Try new package at https://github.com/Road-block/MizusRaidTracker/releases/latest

and report back :)

**Comment by tehKD** [comment]
it works. thanks alot :)
